name: Build & upload package

on:
  release:
    types:
      - published

permissions:
  attestations: write
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2
        with:
          attest-build-provenance-github: 'true'

  # Upload to real PyPI on GitHub Releases.
  release:
    name: Publish to PyPI
    environment: PyPI
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
